-- Question 3

CREATE TABLE [Q3T1] ([Key1] INT PRIMARY KEY, [Value] CHAR)
INSERT INTO [Q3T1] ([Key1],[Value]) VALUES (1,'A')
INSERT INTO [Q3T1] ([Key1],[Value]) VALUES (2,'B')

CREATE TABLE [Q3T2] ([Key2] INT PRIMARY KEY, [Value] CHAR)
INSERT INTO [Q3T2] ([Key2],[Value]) VALUES (2,'X')
INSERT INTO [Q3T2] ([Key2],[Value]) VALUES (3,'Y')

-- Answer 3-1
INSERT Q3T1 (KEY1, VALUE)
SELECT DISTINCT KEY2, VALUE
FROM Q3T2 CR
WHERE
   NOT EXISTS (SELECT * FROM Q3T1 C
              WHERE CR.KEY2 = C.KEY1)


-- Answer 3-2
UPDATE Q3T1 SET VALUE = T2.VALUE
FROM Q3T1 AS T1 
INNER JOIN Q3T2 AS T2
ON T1.KEY1 = T2.KEY2

-- Answer 3-3
DELETE Q3T1  WHERE KEY1 NOT IN (SELECT DISTINCT KEY2 FROM Q3T2)


