-- Question 4

CREATE TABLE [Names] 
	(
	[Id] INT PRIMARY KEY,
	[Name] VARCHAR(100)
	)

CREATE TABLE [Relationships]
	(
	[Child] [int] REFERENCES [Names]([Id]), 
	[Parent] [int] REFERENCES [Names]([Id])
	)

INSERT [NAMES] VALUES (1,'FRANK')
INSERT [NAMES] VALUES (2,'JO')
INSERT [NAMES] VALUES (3,'MARY')
INSERT [NAMES] VALUES (4,'PETER')
INSERT [NAMES] VALUES (5,'MAY')

INSERT [RELATIONSHIPS] VALUES (1,NULL)
INSERT [RELATIONSHIPS] VALUES (2,1)
INSERT [RELATIONSHIPS] VALUES (3,2)
INSERT [RELATIONSHIPS] VALUES (4,1)
INSERT [RELATIONSHIPS] VALUES (5,2)


;WITH 
CTE AS 
    (SELECT ID, NAME, ISNULL(PARENT,0) AS LEVEL
    FROM NAMES N
        LEFT JOIN RELATIONSHIPS R
            ON R.CHILD = N.ID),
R_CTE AS 
    (SELECT 0 AS LVL, ID, NAME, LEVEL
    FROM CTE
    WHERE LEVEL = 0
    UNION ALL
    SELECT R.LVL + 1, C.ID, C.NAME, C.LEVEL
    FROM CTE C
        INNER JOIN R_CTE R
            ON C.LEVEL = R.ID
    )
SELECT * FROM R_CTE
