--Question 1
--Table creation
CREATE TABLE Q1T1 (TEST_ID INT IDENTITY(1,1))

--Insert 100 records
DECLARE @ID INT 
SELECT @ID = 1
WHILE @ID >=1 AND @ID <= 100
BEGIN
    INSERT INTO Q1T1 DEFAULT VALUES SELECT @ID 
	SET @ID = @ID + 1
END
